/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PoCW_ControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "oracleAddress"
      | "sbtContract"
      | "strictSender"
      | "usedNonces"
      | "verifyAndMint"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sbtContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strictSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedNonces",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndMint",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      string,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sbtContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strictSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedNonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndMint",
    data: BytesLike
  ): Result;
}

export interface PoCW_Controller extends BaseContract {
  connect(runner?: ContractRunner | null): PoCW_Controller;
  waitForDeployment(): Promise<this>;

  interface: PoCW_ControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  sbtContract: TypedContractMethod<[], [string], "view">;

  strictSender: TypedContractMethod<[], [boolean], "view">;

  usedNonces: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyAndMint: TypedContractMethod<
    [
      user: AddressLike,
      contentId: BigNumberish,
      score: BigNumberish,
      expiry: BigNumberish,
      nonce: BytesLike,
      tokenUri: string,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sbtContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "strictSender"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "usedNonces"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyAndMint"
  ): TypedContractMethod<
    [
      user: AddressLike,
      contentId: BigNumberish,
      score: BigNumberish,
      expiry: BigNumberish,
      nonce: BytesLike,
      tokenUri: string,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
