/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoCW_SBT,
  IPoCW_SBTInterface,
} from "../../../contracts/PoCW_Controller.sol/IPoCW_SBT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "setTokenURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPoCW_SBT__factory {
  static readonly abi = _abi;
  static createInterface(): IPoCW_SBTInterface {
    return new Interface(_abi) as IPoCW_SBTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPoCW_SBT {
    return new Contract(address, _abi, runner) as unknown as IPoCW_SBT;
  }
}
